from Tkinter import *
from mkwid import *
import winsound
import sys
def end():
	showwarning("think..","if you exit you will lose all levels")
	win=Toplevel()
	win.grab_set()
	win.title("bye")
	Label(win,text="do you really want to exit??\n").pack()
	Button(win,text="yes",command=(lambda:sys.exit(0)),fg='white',bg='tomato').pack(side=LEFT)
	Button(win,text="cancel",command=(lambda:win.destroy()),fg='white',bg='tomato').pack(side=RIGHT)
root=Tk()
root.resizable(0,0)
root.minsize(100,100)
root.title("CINEfreak")	
def goto():
	wid=Toplevel()
	wid.grab_set()
	wid.resizable(0,0)
	var=IntVar()
	Label(wid,text="choose level").pack()
	Radiobutton(wid,text="level 1",value=1,command=(lambda:temp(root,wid,1))).pack()
	Radiobutton(wid,text="level 2",value=2,command=(lambda:temp(root,wid,2))).pack()
	Radiobutton(wid,text="level 3",value=3,command=(lambda:temp(root,wid,3))).pack()
def instruction():
	text=" \twelcome to CINEfreak\n\t-------------------------------\n\nYou will get here different types of movies...\nEvery time you get a movie whose every character except vowels are hidden ..You have to find hidden characters\nDifferent levels contain different movies.\nlevel 1 :  this level contain some easy and famous bollywood movies.\nlevel 2 : this level contain famous hollywood movies.\nlevel 3: this level have old and not so popular movies\n\nafter clearing every movie you will get download link to that movie.\nmake sure that you are typing one word at a time otherwise you will get error.\nyou can also use hint about movie..\nyou can use 3 hints for a movie\nbut remember it can deduce your points\nyou need a cutoff score to enter in any level.\nif you think you have sufficient score to skip a intermediate level,you can jump into higher.\ncutoff score to level 1 = 0\ncutoff score to level 2 = 50\ncutoff score to level 3=100\nif your chances finished ..you can get more chance in cost of points each chance cost 50 points.and also increase points at cost of chance\nyou can play any level only atmost two times.."
	win=Toplevel()
	win.grab_set()
	win.title("CINEfreak help..")
	win.resizable(0,0)
	f=Frame(win)
	mess=Text(f,font=('times',10,'bold'),height=10,width=50)
	mess.insert(INSERT,text)
	bar=Scrollbar(win)
	bar.config(command=mess.yview)
	mess.config(yscrollcommand=bar.set)
	mess.pack(side=TOP)
	f.pack(side=LEFT)
	bar.pack(side=RIGHT,fill=Y)
	Button(f,text="got it..",command=(lambda:win.destroy()),bg='tomato').pack(side=BOTTOM)
def about():
	wid=Toplevel()
	wid.grab_set()
	wid.resizable(0,0)
	Label(wid,text="Author : ROHIT BHARDWAJ").pack()
	Label(wid,text="Language used : python,tkinter").pack()
	Label(wid,text="made on linux").pack()
	Button(wid,text="cancel",bg='tomato',command=(lambda:wid.destroy())).pack()
menubar=Menu(root,bg="light slate blue")
moremenu=Menu(menubar,tearoff=0)
moremenu.add_command(label="goto level..",command=goto)
moremenu.add_command(label="about game",command=about)
helpmenu=Menu(menubar,tearoff=0)
helpmenu.add_command(label="instruction",command=instruction)
menubar.add_cascade(label="help",menu=helpmenu)
getchance=Menu(menubar,tearoff=0)
getchance.add_command(label="add_chance",command=addc)
getchance.add_command(label="add_point",command=addp)
menubar.add_cascade(label="add",menu=getchance)
exitmenu=Menu(menubar,tearoff=0)
exitmenu.add_command(label="exit",command=end)
menubar.add_cascade(label="More",menu=moremenu)
menubar.add_cascade(label="exit",menu=exitmenu)
def main_r(root,main):
	showinfo("see help","Be sure that you have read out all instructions in help menu")
	destroy(root,0,main)
def init(root):
	global main
	text="\nThis is movies quiz\nIf you are movies freak this is for u\nanswer here different HOLLYWOOD/BOLLYWOOD movies...\nAND win excited gifts!!!!"
	main=LabelFrame(root,text="WELCOME TO CINEfreak",labelanchor='n',font=('times',25,'bold'),bg='brown',fg='antique white')
	main.pack(expand=YES,fill=BOTH)
	Label(main,text=text,font=('times',15,'italic'),bg='aquamarine').pack(expand=YES,fill=BOTH)
	Label(main,text="this game is developed by\n'ROHIT BHARDWAJ'",font=('times',15,'italic'),bg='aquamarine').pack(expand=YES,fill=BOTH)
	Button(main,text="play now",command=(lambda:main_r(root,main)),fg='white',bg='black').pack()
init(root)
winsound.PlaySound('yourfile.wav', winsound.SND_ASYNC|winsound.SND_LOOP)
root.config(menu=menubar)	
root.mainloop()   
